power2 <- read.csv("Y:/personal/personal/Work/teaching/Data Science/Coursera/household_power_consumption.txt", sep=";", quote="", stringsAsFactors=FALSE)
power1<-subset(power2, Date=="1/2/2007")
power2<-subset(power2, Date=="2/2/2007")
powerc<-rbind(power1, power2)
time<-paste(powerc$Date, powerc$Time)
time1<-strptime(time, "%e/%m/%Y %H:%M:%S")
png(file="plot2.png")
plot(time1, as.numeric(powerc$Global_active_power), type="n", ylab = "Global Active Power(kilowatts)")
lines(time1,as.numeric(powerc$Global_active_power), type="l")
dev.off()
