power2 <- read.csv("Y:/personal/personal/Work/teaching/Data Science/Coursera/household_power_consumption.txt", sep=";", quote="", stringsAsFactors=FALSE)
power1<-subset(power2, Date=="1/2/2007")
power2<-subset(power2, Date=="2/2/2007")
powerc<-rbind(power1, power2)
time<-paste(powerc$Date, powerc$Time)
time1<-strptime(time, "%e/%m/%Y %H:%M:%S")
#png(file="plot4.png")
par(mfrow=c(2,2))
plot(time1, as.numeric(powerc$Global_active_power), type="n", ylab = "Global Active Power(kilowatts)")
lines(time1,as.numeric(powerc$Global_active_power), type="l")
plot(time1, as.numeric(powerc$Voltage), type="n", ylab = "Voltage", xlab="datetime")
lines(time1,as.numeric(powerc$Voltage), type="l")
plot(time1, as.numeric(powerc$Sub_metering_1), type="s", ylab = "Energy submetering")
lines(time1,as.numeric(powerc$Sub_metering_2), type="s", col="red")
lines(time1,as.numeric(powerc$Sub_metering_3), type="s", col="blue")
legend("topright",c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"), lty=1, col=c("black", "red","blue"),bty="n" )

#dev.off()
